AllCops:
  TargetRubyVersion: 2.7

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/CyclomaticComplexity:
  Enabled: true

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - "**/*.gemspec"
    - "spec/**/*"

Layout/LineLength:
  Max: 80
  Exclude:
    - "**/*.gemspec"
    - "spec/**/*"

Naming/MemoizedInstanceVariableName:
   EnforcedStyleForLeadingUnderscores: optional

Gemspec/RequiredRubyVersion:
  Enabled: false
