AllCops:
  TargetRubyVersion: 2.7

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/CyclomaticComplexity:
  Enabled: true

Metrics/MethodLength:
  Max: 20

Layout/LineLength:
  Max: 80

Naming/MemoizedInstanceVariableName:
   EnforcedStyleForLeadingUnderscores: optional
