AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: true

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"
    - "*.gemspec"

Layout/LineLength:
  Exclude:
    - "spec/**/*_spec.rb"
    - "*.gemspec"

Naming/MemoizedInstanceVariableName:
   EnforcedStyleForLeadingUnderscores: optional
