name: audit

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - master

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
      - name: Setup
        run : |
          gem install bundler bundler-audit
          bundle install
      - name: Run Bundler Audit
        run : bundle audit --update
